= OSP 10 - All in one
Miguel Pineda <mpinedam@redhat.com>
v1.0, 2017-12-19
:doctype: book
:keywords: Asciidoctor, samples, e-book, EPUB3, KF8, MOBI, Asciidoctor.js


////
*Comment* 
S10 ctr01    - f2lctr01.act.com.mx        10.10.205.23 10.17.32.10 
S11 ctr02    - f2lctr02.act.com.mx        10.10.205.24 10.17.32.11
S9 compute01 - f2lcompute01.act.com.mx    10.10.205.19 10.17.32.12
S7 compute02 - f2lcompute02.act.com.mx    10.10.205.20 10.17.32.13
S6 compute03 - f2lcompute03.act.com.mx    10.10.205.21 10.17.32.14
V1             v1plsatellite01.act.com.mx 10.10.110.21
V2             v2plntpserver01.act.com.mx 10.10.113.50
Actinver01
////

== 1 .- Resumen de Laboratorio

Con la finalidad de proveer de una plataforma de funcionalidades IaaS, Red Hat apoya a
Grupo Financiero Actinver implementando los siguientes componentes en un
ambiente de laboratorio :

* Red Hat Openstack Platform v10+u con Packstack.

Dicho laboratorio esta diseñado para acercar lo mas posible la funcionalidad actual a un
ambiente de Desarrollo ó Pruebas.

El laboratorio consta de una implementación estándar por lo cual no se realizó ninguna tarea
adicional (tunning) a ninguno de los componentes, no se contemplaron tareas de
benckmarking, por lo cual sí el cliente requiere obtener métricas de consumo, performance o
sizing, se tendrán que realizar tareas en una definición externa a este documento.

IMPORTANT: Este laboratorio se realizó con Packstack debido a que durante la instalación con
                       OSP Director las interfaces de red de los servidores IBM x240 8737AC1 durante el
                       proceso introspección no realizaban el proceso adecuado de descarga de imagenes,
                       Actualmente se tiene un ticket abierto con Red Hat sin embargo todo apunta a un 
                       problema de HW.


=== Componentes del entorno de laboratorio

* Una estación de trabajo cliente.
* Dos nodos control
* Tres nodos de computo

==== Designaciones de nodos

Los comandos se deben ejecutar en nodos específicos. Cada paso menciona el nodo o los nodos en los que se debe ejecutar entre corchetes, de la siguiente manera:

* [Control]
* [Computo]

Por ejemplo:

Ejecute este comando en los nodos *Control* y en el nodo *Computo*:

*[Control01-02]* *[Computo01-03]*

----
# yum install ntp
----

.Segmentación de equipos
[options="header,footer"]
|=======================
| Server No.  | Hostname       |Rol        |Ip MGNT      |Ip Publica / mask /gw/dns  | interfaz
|S6  | ctr01.example.com       |Controller |10.10.205.19 |10.12.8.11/24/10.12.8.254/10.11.9.250 |4 y 5
|S7  | ctr02.example.com       |Controller |10.10.205.20 |10.12.8.12/24/10.12.8.254/10.11.9.250 |4 y 5
|S9  | compute01.example.com   |Compute    |10.10.205.21 |10.12.8.13/24/10.12.8.254/10.11.9.250 |4 y 5
|S11 | compute02.example.com   |Compute    |10.10.205.23 |10.12.8.14/24/10.12.8.254/10.11.9.250 |4 y 5 
|S12 | compute03.example.com   |Compute    |10.10.205.24 |10.12.8.15/24/10.12.8.254/10.11.9.250 |4 y 5 
|    | satellite01.example.com |Satellite  |10.10.110.21 |    N/A
|    | ntp.example.com.        |NTP        |10.10.113.50 |
|=======================

== 2 .- Preparando Ambiente de Laboratorio.

=== 1.- Validando canales/repositorios necesarios.
En los nodos de Control, Computo, valide que tiene los repositorios necesarios para la instalación:

*[Control01-02]* *[Computo01-03]*

----
# yum repolist
----

* Salida Esperada:
+
[source,bash]
-----------------
repo id                                  repo name                                          status
rhel-7-server-extras-rpms                RH Enterprise Linux 7 Server Extras               76
rhel-7-server-openstack-10-devtools-rpms RH OpenStack 10 DevTools                           3
rhel-7-server-openstack-10-rpms          RH OpenStack 10                                  680
rhel-7-server-rh-common-rpms             RH Enterprise Linux 7 Common                      77
rhel-7-server-rpms                       RH Enterprise Linux 7                          4,874
rhel-ha-for-rhel-7-server-rpms           RH Enterprise Linux 7 Server High-Availability    37
repolist: 5,747
-----------------


TIP: Red Hat actualiza periódicamente sus repositorios, por lo que la cantidad de paquetes puede variar de los que se muestran arriba. 
     Lo mismo para versiones de productos menores o superiores.
     
=== 2.- Actualizar nodos:

Antes de comenzar los laboratorios restantes, asegúrese de que sus paquetes estén actualizados.

a)  Actualize los paquetes en todos los nodos

*[Control01-02]* *[Computo01-03]*

----
# yum -y update
----

* Salida Esperada:
+
[source,bash]
-----------------
repo id
-----------------

b) En caso de tener una nueva versión de Kernel, reinicie los nodos:

----
# reboot
----

=== 3.- Instalar Utilerias de OpenStack.

OpenStack requiere unos pocos paquetes base y definiciones de políticas (SELinux) en todos los nodos.

a) Como *root*, ejecute el siguiente comando en todos los nodos:

*[Control01-02]* *[Computo01-03]*

----
# yum -y install openstack-utils openstack-selinux
----       
       
=== 4.- Configurando Firewall

a) Instale el paquete iptables-services en todos los nodos:

*[Control01-03]* *[Computo01-03]*

----
# yum -y install iptables-services
----

b) Iniciar y habilitar los servicios de iptables e ip6tables.

*[Control01-02]* *[Compute01-03]*

----
# systemctl start iptables.service ip6tables.service
# systemctl enable iptables.service ip6tables.service
----

=== 5.- Configurar NTP Server en nodo Controller.

a) Vea el archivo /etc/ntp.conf y asegúrese de que contiene las siguientes declaraciones del servidor:

*[Control01]*

* Salida Esperada:
+
[source,bash]
-----------------
server 10.10.113.50 iburst
-----------------
    
b) En la parte superior del archivo, comente las tres líneas de restricción para permitir el acceso y agregue lo siguiente:

*[Control01]*

----
restrict -4 default kod notrap nomodify
restrict -6 default kod notrap nomodify
----

c) Guarde y cierre el archivo

d) Inicie y habilite el servicio de NTP.

*[Control01]*

----
# systemctl enable ntpd.service
# systemctl start ntpd.service
----

e) abra el archivo /etc/sysconfig/iptables con un editor de textos.

f) Agregue una regla de entrada que permita el tráfico UDP en el puerto 123 para que el servidor NTP pueda responder las consultas que le realicen.

*[Control01]*

----
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
----

g) Reinicie el servicio de iptables y verifique la configuración:

*[Control01]*

----
# systemctl restart iptables.service
# iptables -L
----

* Salida Esperada:
+
[source,bash]
-----------------
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
-----------------

=== 6.- Configurando NTP en nodos Control y Compute.

a) En los nodos Compute y el nodo Almacenamiento, instale los paquetes NTP requeridos:

b) Edite el archivo /etc/ntp.conf para que la declaración del servidor apunte a su nodo Control.

*[Control02]* *[Computo01-03]*
----
server ctrl.example.com iburst
----

c) Guarde y Cierre el Archivo.

d) Inicie y habilite el servicio de NTP. 

*[Control02]* *[Computo01-03]*

----
# systemctl enable ntpd.service
# systemctl start ntpd.service
----

=== 7 Deshabilitando Network Manager

En esta sección, primero deshabilite Network Manager en su nodo Controller, Compute nodes. Luego habilite e inicie el servicio de *network* estándar.

a) Como usuario root, detenga y deshabilite el servicio de Network Manager:

*[Control01-02]* *[Computo01-03]*

----
# systemctl stop NetworkManager.service
# systemctl disable NetworkManager.service
----

b) Asegúrese de que el servicio *network* tome el control de las interfaces estableciendo la opción NM_CONTROLLED en "no":

*[Control01-02]* *[Computo01-03]*

----
echo 'NM_CONTROLLED="no"' | tee -a /etc/sysconfig/network-scripts/ifcfg-eth0

----

c) Reinicie los nodos.

*[Control01-02]* *[Computo01-03]*

----
# reboot
----

== 3 .- Laboratorio Packstack.


















