== OSP10 - AIO
:Author:    Miguel Angel Pineda
:Email:     <mpinedam@redhat.com>
:Date: 19-Dic-2017
:Revision:  1.2

Autor:   {author}

Versión: {revision}

////
*Comment* 
S10 ctr01 - f2lctr01.actinver.com.mx 10.10.205.23 10.17.32.10 
S11 ctr02 - f2lctr02.actinver.com.mx 10.10.205.24 10.17.32.11
S9 compute01 - f2lcompute01.actinver.com.mx 10.10.205.19 10.17.32.12
S7 compute02 - f2lcompute02.actinver.com.mx 10.10.205.20 10.17.32.13
S6 compute03 - f2lcompute03.actinver.com.mx 10.10.205.21 10.17.32.14
V1 v1plsatellite01.actinver.com.mx 
////

=== 1 .- Resumén de Laboratorio.

Con la finalidad de proveer de una plataforma de funcionalidades IaaS, Red Hat apoya a
Grupo Financiero Actinver implementando los siguientes componentes en un
ambiente de laboratorio :

* Red Hat Openstack Platform v10+u con Packstack.

Dicho laboratorio esta diseñado para acercar lo mas posible la funcionalidad actual a un
ambiente de Desarrollo ó Pruebas.

El laboratorio consta de una implementación estándar por lo cual no se realizó ninguna tarea
adicional (tunning) a ninguno de los componentes, no se contemplaron tareas de
benckmarking, por lo cual sí el cliente requiere obtener métricas de consumo, performance o
sizing, se tendrán que realizar tareas en una definición externa a este documento.

IMPORTANT: Este laboratorio se realizó con Packstack debido a que durante la instalación con
                       OSP Director las interfaces de red de los servidores IBM x240 8737AC1 durante el
                       proceso introspección no realizaban el proceso adecuado de descarga de imagenes,
                       Actualmente se tiene un ticket abierto con Red Hat sin embargo todo apunta a un 
                       problema de HW.


==== Componentes del entorno de laboratorio

* Una estación de trabajo cliente.
* Dos nodos control
* Tres nodos de computo

==== Designaciones de nodos

Los comandos se deben ejecutar en nodos específicos. Cada paso menciona el nodo o los nodos en los que se debe ejecutar entre corchetes, de la siguiente manera:

* [Control]
* [Computo]

Por ejemplo:

Ejecute este comando en los nodos *Control* y en el nodo *Computo*:

*[Control]* *[Computo]*

----
# yum install ntp
----

.Segmentación de equipos
[options="header,footer"]
|=======================
| Server No.  | Hostname       |Rol        |Ip MGNT      |Ip Public
|S6  | ctr01.example.com       |Controller |10.10.205.19 |10.12.8.11
|S7  | ctr02.example.com       |Controller |10.10.205.20 |10.12.8.12
|S9  | compute01.example.com   |Compute    |10.10.205.21 |10.12.8.13
|S11 | compute02.example.com   |Compute    |10.10.205.23 |10.12.8.14
|S12 | compute03.example.com   |Compute    |10.10.205.23 |10.12.8.15
|    | satellite01.example.com |Satellite  |10.10.110.21 |    N/A
|=======================

=== 2 .- Preparando Ambiente de Laboratorio.

En los nodos de Control, Computo, valide que tiene los repositorios necesarios para la instalación:

*[Control]* *[Computo]*

----
# yum repolist
----

* Salida Esperada:
+
[source,bash]
-----------------
repo id                                  repo name                                          status
rhel-7-server-extras-rpms                RH Enterprise Linux 7 Server Extras               76
rhel-7-server-openstack-10-devtools-rpms RH OpenStack 10 DevTools                           3
rhel-7-server-openstack-10-rpms          RH OpenStack 10                                  680
rhel-7-server-rh-common-rpms             RH Enterprise Linux 7 Common                      77
rhel-7-server-rpms                       RH Enterprise Linux 7                          4,874
rhel-ha-for-rhel-7-server-rpms           RH Enterprise Linux 7 Server High-Availability    37
repolist: 5,747
-----------------


TIP: Red Hat actualiza periódicamente sus repositorios, por lo que la cantidad de paquetes puede variar de los que se muestran arriba. 
     Lo mismo para versiones de productos menores o superiores.
     
==== 1.- Actualizar nodos:

Antes de comenzar los laboratorios restantes, asegúrese de que sus paquetes estén actualizados.

a)  Actualize los paquetes en todos los nodos

*[Control]* *[Computo]*

----
# yum -y update
----

* Salida Esperada:
+
[source,bash]
-----------------
repo id
-----------------

b) En caso de tener una nueva versión de Kernel, reinicie los nodos:

----
# reboot
----

==== 2.- Instalar Utilerias de OpenStack.

OpenStack requiere unos pocos paquetes base y definiciones de políticas (SELinux) en todos los nodos.

    a) Como *root*, ejecute el siguiente comando en todos los nodos:
       *[Control]* *[Computo]*
----
# yum -y install openstack-utils openstack-selinux
----       
       
    b) 
    
    c)