= OSP 10 - All in one
Miguel Pineda <mpinedam@redhat.com>
v1.0, 2017-12-19
:doctype: book
:keywords: Asciidoctor, samples, e-book, EPUB3, KF8, MOBI, Asciidoctor.js


////
*Comment* 
S10 ctr01    - f2lctr01.act.com.mx        10.10.205.23 10.17.32.10 
S11 ctr02    - f2lctr02.act.com.mx        10.10.205.24 10.17.32.11
S9 compute01 - f2lcompute01.act.com.mx    10.10.205.19 10.17.32.12
S7 compute02 - f2lcompute02.act.com.mx    10.10.205.20 10.17.32.13
S6 compute03 - f2lcompute03.act.com.mx    10.10.205.21 10.17.32.14
V1             v1plsatellite01.act.com.mx 10.10.110.21
V2             v2plntpserver01.act.com.mx 10.10.113.50
Actinver01
////

== 1 .- Resumen de Laboratorio

Con la finalidad de proveer de una plataforma de funcionalidades IaaS, Red Hat apoya a
Grupo Financiero Actinver implementando los siguientes componentes en un
ambiente de laboratorio :

* Red Hat Openstack Platform v10+u con Packstack.

Dicho laboratorio esta diseñado para acercar lo mas posible la funcionalidad actual a un
ambiente de Desarrollo ó Pruebas.

El laboratorio consta de una implementación estándar por lo cual no se realizó ninguna tarea
adicional (tunning) a ninguno de los componentes, no se contemplaron tareas de
benckmarking, por lo cual sí el cliente requiere obtener métricas de consumo, performance o
sizing, se tendrán que realizar tareas en una definición externa a este documento.

IMPORTANT: Este laboratorio se realizó con Packstack debido a que durante la instalación con
                       OSP Director las interfaces de red de los servidores IBM x240 8737AC1 durante el
                       proceso introspección no realizaban el proceso adecuado de descarga de imagenes,
                       Actualmente se tiene un ticket abierto con Red Hat sin embargo todo apunta a un 
                       problema de HW.


=== Componentes del entorno de laboratorio

* Una estación de trabajo cliente.
* Dos nodos control
* Tres nodos de computo

==== Designaciones de nodos

Los comandos se deben ejecutar en nodos específicos. Cada paso menciona el nodo o los nodos en los que se debe ejecutar entre corchetes, de la siguiente manera:

* [Control]
* [Computo]

Por ejemplo:

Ejecute este comando en los nodos *Control* y en el nodo *Computo*:

*[Control01-02]* *[Computo01-03]*

----
# yum install ntp
----

.Segmentación de equipos
[options="header,footer"]
|=======================
| Server No.  | Hostname       |Rol        |Ip MGNT      |Ip Publica / mask /gw/dns  | interfaz
|S6  | ctr01.example.com       |Controller |10.10.205.19 |10.12.8.11/24/10.12.8.254/10.11.9.250 |4 y 5
|S7  | ctr02.example.com       |Controller |10.10.205.20 |10.12.8.12/24/10.12.8.254/10.11.9.250 |4 y 5
|S9  | compute01.example.com   |Compute    |10.10.205.21 |10.12.8.13/24/10.12.8.254/10.11.9.250 |4 y 5
|S11 | compute02.example.com   |Compute    |10.10.205.23 |10.12.8.14/24/10.12.8.254/10.11.9.250 |4 y 5 
|S12 | compute03.example.com   |Compute    |10.10.205.24 |10.12.8.15/24/10.12.8.254/10.11.9.250 |4 y 5 
|    | satellite01.example.com |Satellite  |10.10.110.21 |    N/A
|    | ntp.example.com.        |NTP        |10.10.113.50 |
|=======================

== 2 .- Preparando Ambiente de Laboratorio.

=== 1.- Validando canales/repositorios necesarios.
En los nodos de Control, Computo, valide que tiene los repositorios necesarios para la instalación:

*[Control01-02]* *[Computo01-03]*

----
# yum repolist
----

* Salida Esperada:
+
[source,bash]
-----------------

Complementos cargados:enabled_repos_upload, package_upload, product-id, search-disabled-repos,
                    : subscription-manager
nombre del repositorio                                  estado
rhel-7-server-extras-rpms/x86_64                        RH Enterprise Linux 7 Server     710
rhel-7-server-openstack-10-devtools-rpms/7Server/x86_64 RH OpenStack Platform 10 Deve      8
rhel-7-server-openstack-10-optools-rpms/7Server/x86_64  RH OpenStack Platform 10 Oper     99
rhel-7-server-openstack-10-rpms/7Server/x86_64          RH OpenStack Platform 10 for   1 711
rhel-7-server-rh-common-rpms/7Server/x86_64             RH Enterprise Linux 7 Server     231
rhel-7-server-rpms/7Server/x86_64                       RH Enterprise Linux 7 Server  17 802
rhel-7-server-satellite-tools-6.2-rpms/x86_64           RH Satellite Tools 6.2 (for R    132
rhel-ha-for-rhel-7-server-rpms/7Server/x86_64           RH Enterprise Linux High Avai    391
repolist: 21 084
Uploading Enabled Repositories Report
Complementos cargados:product-id, subscription-manager


-----------------


TIP: Red Hat actualiza periódicamente sus repositorios, por lo que la cantidad de paquetes puede variar de los que se muestran arriba. 
     Lo mismo para versiones de productos menores o superiores.
     
=== 2.- Actualizar nodos:

Antes de comenzar los laboratorios restantes, asegúrese de que sus paquetes estén actualizados.

a)  Actualize los paquetes en todos los nodos

*[Control01-02]* *[Computo01-03]*

----
# yum -y update
----

* Salida Esperada:
+
[source,bash]
-----------------
[root@f2lctr01 ~]# yum -y update
Complementos cargados:enabled_repos_upload, package_upload, product-id, search-disabled-repos,
                    : subscription-manager
rhel-7-server-openstack-10-devtools-rpms                                  | 2.3 kB  00:00:00     
rhel-7-server-openstack-10-optools-rpms                                   | 2.3 kB  00:00:00     
Resolviendo dependencias
--> Ejecutando prueba de transacción                                                                                                                                                                                                                                         
---> Paquete pyOpenSSL.x86_64 0:0.13.1-3.el7 debe ser obsoleto
---> Paquete python-dateutil.noarch 0:1.5-7.el7 debe ser actualizado
---> Paquete python-dateutil.noarch 1:2.4.2-1.el7ost debe ser una actualización
--> Procesando dependencias: python-six para el paquete: 1:python-dateutil-2.4.2-1.el7ost.noarch
---> Paquete python-lxml.x86_64 0:3.2.1-4.el7 debe ser actualizado
---> Paquete python-lxml.x86_64 0:3.2.1-5.el7ost debe ser una actualización
---> Paquete python-pyOpenSSL.noarch 0:16.2.0-3.el7ost debe ser obsoleto
--> Procesando dependencias: python-cryptography >= 1.3.0 para el paquete: python-pyOpenSSL-16.2.0-3.el7ost.noarch
--> Ejecutando prueba de transacción                                                                                                                                                                                                                                         
---> Paquete python-six.noarch 0:1.9.0-2.el7 debe ser instalado
---> Paquete python2-cryptography.x86_64 0:1.7.2-1.el7_4.1 debe ser instalado
--> Procesando dependencias: python-pyasn1 >= 0.1.8 para el paquete: python2-cryptography-1.7.2-1.el7_4.1.x86_64
--> Procesando dependencias: python-idna >= 2.0 para el paquete: python2-cryptography-1.7.2-1.el7_4.1.x86_64
--> Procesando dependencias: python-cffi >= 1.4.1 para el paquete: python2-cryptography-1.7.2-1.el7_4.1.x86_64
--> Procesando dependencias: python-ipaddress para el paquete: python2-cryptography-1.7.2-1.el7_4.1.x86_64
--> Procesando dependencias: python-enum34 para el paquete: python2-cryptography-1.7.2-1.el7_4.1.x86_64
--> Ejecutando prueba de transacción                                                                                                                                                                                                                                         
---> Paquete python-cffi.x86_64 0:1.6.0-5.el7 debe ser instalado
--> Procesando dependencias: python-pycparser para el paquete: python-cffi-1.6.0-5.el7.x86_64
---> Paquete python-enum34.noarch 0:1.0.4-1.el7 debe ser instalado
---> Paquete python-idna.noarch 0:2.4-1.el7 debe ser instalado
---> Paquete python-ipaddress.noarch 0:1.0.16-2.el7 debe ser instalado
---> Paquete python2-pyasn1.noarch 0:0.1.9-7.el7 debe ser instalado
--> Ejecutando prueba de transacción                                                                                                                                                                                                                                         
---> Paquete python-pycparser.noarch 0:2.14-1.el7 debe ser instalado
--> Procesando dependencias: python-ply para el paquete: python-pycparser-2.14-1.el7.noarch
--> Ejecutando prueba de transacción                                                                                                                                                                                                                                         
---> Paquete python-ply.noarch 0:3.4-11.el7 debe ser instalado
--> Resolución de dependencias finalizada                                                                                                                                                                                        

Dependencias resueltas

 python-pyOpenSSL        noarch    16.2.0-3.el7ost      rhel-7-server-openstack-10-rpms     88 k
     reemplazando  pyOpenSSL.x86_64 0.13.1-3.el7
Actualizando:
 python-dateutil         noarch    1:2.4.2-1.el7ost     rhel-7-server-openstack-10-rpms     84 k
 python-lxml             x86_64    3.2.1-5.el7ost       rhel-7-server-openstack-10-rpms    847 k
Instalando para las dependencias:
 python-cffi             x86_64    1.6.0-5.el7          rhel-7-server-rpms                 218 k
 python-enum34           noarch    1.0.4-1.el7          rhel-7-server-rpms                  52 k
 python-idna             noarch    2.4-1.el7            rhel-7-server-rpms                  94 k
 python-ipaddress        noarch    1.0.16-2.el7         rhel-7-server-rpms                  34 k
 python-ply              noarch    3.4-11.el7           rhel-7-server-rpms                 123 k
 python-pycparser        noarch    2.14-1.el7           rhel-7-server-rpms                 105 k
 python-six              noarch    1.9.0-2.el7          rhel-7-server-rpms                  29 k
 python2-cryptography    x86_64    1.7.2-1.el7_4.1      rhel-7-server-rpms                 502 k
 python2-pyasn1          noarch    0.1.9-7.el7          rhel-7-server-rpms                 100 k

Resumen de la transacción                                                                                                                                                                                                                              
=================================================================================================
Instalar    1 Paquete  (+9 Paquetes dependientes)
Actualizar  2 Paquetes

Tamaño total de la descarga: 2.2 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/12): python-dateutil-2.4.2-1.el7ost.noarch.rpm                         |  84 kB  00:00:00     
(2/12): python-cffi-1.6.0-5.el7.x86_64.rpm                                | 218 kB  00:00:00     
(3/12): python-enum34-1.0.4-1.el7.noarch.rpm                              |  52 kB  00:00:00     
(4/12): python-ipaddress-1.0.16-2.el7.noarch.rpm                          |  34 kB  00:00:00     
(5/12): python-idna-2.4-1.el7.noarch.rpm                                  |  94 kB  00:00:00     
(6/12): python-ply-3.4-11.el7.noarch.rpm                                  | 123 kB  00:00:00     
(7/12): python-pycparser-2.14-1.el7.noarch.rpm                            | 105 kB  00:00:00     
(8/12): python-six-1.9.0-2.el7.noarch.rpm                                 |  29 kB  00:00:00     
(9/12): python-lxml-3.2.1-5.el7ost.x86_64.rpm                             | 847 kB  00:00:00     
(10/12): python-pyOpenSSL-16.2.0-3.el7ost.noarch.rpm                      |  88 kB  00:00:00     
(11/12): python2-cryptography-1.7.2-1.el7_4.1.x86_64.rpm                  | 502 kB  00:00:00     
(12/12): python2-pyasn1-0.1.9-7.el7.noarch.rpm                            | 100 kB  00:00:00     
-------------------------------------------------------------------------------------------------
Total                                                            4.8 MB/s | 2.2 MB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Instalando    : python-six-1.9.0-2.el7.noarch                                             1/15 
  Instalando    : python2-pyasn1-0.1.9-7.el7.noarch                                         2/15 
  Instalando    : python-enum34-1.0.4-1.el7.noarch                                          3/15 
  Instalando    : python-ipaddress-1.0.16-2.el7.noarch                                      4/15 
  Instalando    : python-ply-3.4-11.el7.noarch                                              5/15 
  Instalando    : python-pycparser-2.14-1.el7.noarch                                        6/15 
  Instalando    : python-cffi-1.6.0-5.el7.x86_64                                            7/15 
  Instalando    : python-idna-2.4-1.el7.noarch                                              8/15 
  Instalando    : python2-cryptography-1.7.2-1.el7_4.1.x86_64                               9/15 
  Instalando    : python-pyOpenSSL-16.2.0-3.el7ost.noarch                                  10/15 
  Actualizando  : 1:python-dateutil-2.4.2-1.el7ost.noarch                                  11/15 
  Actualizando  : python-lxml-3.2.1-5.el7ost.x86_64                                        12/15 
  Limpieza      : python-dateutil-1.5-7.el7.noarch                                         13/15 
  Eliminando    : pyOpenSSL-0.13.1-3.el7.x86_64                                            14/15 
  Limpieza      : python-lxml-3.2.1-4.el7.x86_64                                           15/15 
Uploading Package Profile
rhel-7-server-openstack-10-devtools-rpms/7Server/x86_64/productid         | 2.1 kB  00:00:00     
rhel-7-server-openstack-10-optools-rpms/7Server/x86_64/productid          | 2.1 kB  00:00:00     
  Comprobando   : python-idna-2.4-1.el7.noarch                                              1/15 
  Comprobando   : python-pycparser-2.14-1.el7.noarch                                        2/15 
  Comprobando   : python-ply-3.4-11.el7.noarch                                              3/15 
  Comprobando   : python-pyOpenSSL-16.2.0-3.el7ost.noarch                                   4/15 
  Comprobando   : python-lxml-3.2.1-5.el7ost.x86_64                                         5/15 
  Comprobando   : python-cffi-1.6.0-5.el7.x86_64                                            6/15 
  Comprobando   : python-ipaddress-1.0.16-2.el7.noarch                                      7/15 
  Comprobando   : python-enum34-1.0.4-1.el7.noarch                                          8/15 
  Comprobando   : python2-pyasn1-0.1.9-7.el7.noarch                                         9/15 
  Comprobando   : python-six-1.9.0-2.el7.noarch                                            10/15 
  Comprobando   : python2-cryptography-1.7.2-1.el7_4.1.x86_64                              11/15 
  Comprobando   : 1:python-dateutil-2.4.2-1.el7ost.noarch                                  12/15 
  Comprobando   : pyOpenSSL-0.13.1-3.el7.x86_64                                            13/15 
  Comprobando   : python-dateutil-1.5-7.el7.noarch                                         14/15 
  Comprobando   : python-lxml-3.2.1-4.el7.x86_64                                           15/15 

Instalado:
  python-pyOpenSSL.noarch 0:16.2.0-3.el7ost                                                      

Dependencia(s) instalada(s):
  python-cffi.x86_64 0:1.6.0-5.el7           python-enum34.noarch 0:1.0.4-1.el7                  
  python-idna.noarch 0:2.4-1.el7             python-ipaddress.noarch 0:1.0.16-2.el7              
  python-ply.noarch 0:3.4-11.el7             python-pycparser.noarch 0:2.14-1.el7                
  python-six.noarch 0:1.9.0-2.el7            python2-cryptography.x86_64 0:1.7.2-1.el7_4.1       
  python2-pyasn1.noarch 0:0.1.9-7.el7       

Actualizado:
  python-dateutil.noarch 1:2.4.2-1.el7ost           python-lxml.x86_64 0:3.2.1-5.el7ost          

Sustituido(s):
  pyOpenSSL.x86_64 0:0.13.1-3.el7                                                                

¡Listo!
Uploading Enabled Repositories Report
Complementos cargados:product-id, subscription-manager
  

-----------------

b) En caso de tener una nueva versión de Kernel, reinicie los nodos:

----
# reboot
----

=== 3.- Instalar Utilerias de OpenStack.

OpenStack requiere unos pocos paquetes base y definiciones de políticas (SELinux) en todos los nodos.

a) Como *root*, ejecute el siguiente comando en todos los nodos:

*[Control01-02]* *[Computo01-03]*

----
# yum -y install openstack-utils openstack-selinux
----       
       
=== 4.- Configurando Firewall

a) Instale el paquete iptables-services en todos los nodos:

*[Control01-03]* *[Computo01-03]*

----
# yum -y install iptables-services
----

b) Iniciar y habilitar los servicios de iptables e ip6tables.

*[Control01-02]* *[Compute01-03]*

----
# systemctl start iptables.service ip6tables.service
# systemctl enable iptables.service ip6tables.service
----

=== 5.- Configurar NTP Server en nodo Controller.

a) Vea el archivo /etc/ntp.conf y asegúrese de que contiene las siguientes declaraciones del servidor:

*[Control01]*

* Salida Esperada:
+
[source,bash]
-----------------
server 10.10.113.50 iburst
-----------------
    
b) En la parte superior del archivo, comente las tres líneas de restricción para permitir el acceso y agregue lo siguiente:

*[Control01]*

----
restrict -4 default kod notrap nomodify
restrict -6 default kod notrap nomodify
----

c) Guarde y cierre el archivo

d) Inicie y habilite el servicio de NTP.

*[Control01]*

----
# systemctl enable ntpd.service
# systemctl start ntpd.service
----

e) abra el archivo /etc/sysconfig/iptables con un editor de textos.

f) Agregue una regla de entrada que permita el tráfico UDP en el puerto 123 para que el servidor NTP pueda responder las consultas que le realicen.

*[Control01]*

----
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
----

g) Reinicie el servicio de iptables y verifique la configuración:

*[Control01]*

----
# systemctl restart iptables.service
# iptables -L
----

* Salida Esperada:
+
[source,bash]
-----------------
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
-----------------

=== 6.- Configurando NTP en nodos Control y Compute.

a) En los nodos Compute y el nodo Almacenamiento, instale los paquetes NTP requeridos:

b) Edite el archivo /etc/ntp.conf para que la declaración del servidor apunte a su nodo Control.

*[Control02]* *[Computo01-03]*
----
server ctrl.example.com iburst
----

c) Guarde y Cierre el Archivo.

d) Inicie y habilite el servicio de NTP. 

*[Control02]* *[Computo01-03]*

----
# systemctl enable ntpd.service
# systemctl start ntpd.service
----

=== 7 Deshabilitando Network Manager

En esta sección, primero deshabilite Network Manager en su nodo Controller, Compute nodes. Luego habilite e inicie el servicio de *network* estándar.

a) Como usuario root, detenga y deshabilite el servicio de Network Manager:

*[Control01-02]* *[Computo01-03]*

----
# systemctl stop NetworkManager.service
# systemctl disable NetworkManager.service
----

b) Asegúrese de que el servicio *network* tome el control de las interfaces estableciendo la opción NM_CONTROLLED en "no":

*[Control01-02]* *[Computo01-03]*

----
echo 'NM_CONTROLLED="no"' | tee -a /etc/sysconfig/network-scripts/ifcfg-eth0

----

c) Reinicie los nodos.

*[Control01-02]* *[Computo01-03]*

----
# reboot
----

== 3 .- Laboratorio Packstack.




[root@f2lctr01 ~]# yum install openstack-packstackComplementos cargados:enabled_repos_upload, package_upload,
                    : product-id, search-disabled-repos,
                    : subscription-manager
rhel-7-server-extras-rpms                 | 2.0 kB     00:00     
rhel-7-server-openstack-10-devtools-rpms  | 2.3 kB     00:00     
rhel-7-server-openstack-10-optools-rpms   | 2.3 kB     00:00     
rhel-7-server-openstack-10-rpms           | 2.3 kB     00:00     
rhel-7-server-rh-common-rpms              | 2.1 kB     00:00     
rhel-7-server-rpms                        | 2.0 kB     00:00     
rhel-7-server-satellite-tools-6.2-rpms    | 2.1 kB     00:00     
rhel-ha-for-rhel-7-server-rpms            | 2.0 kB     00:00     
El paquete 1:openstack-packstack-9.0.3-4.el7ost.noarch ya se encuentra instalado con su versión más reciente
Nada para hacer
Uploading Enabled Repositories Report
Complementos cargados:product-id, subscription-manager
[root@f2lctr01 ~]# 




[root@f2lctr01 ~]# ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa): 
/root/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /root/.ssh/id_rsa.
Your public key has been saved in /root/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:M13MAJsIA3rWgQoKLkNERlKXb8LLQJB3aFrbWwkeP+k root@f2lctr01.actinver.com.mx
The key's randomart image is:
+---[RSA 2048]----+
|*Oo+=.  ...      |
|*oBo=+ . o +     |
|BBo*.=.oo   +    |
|*+o = O  . .     |
|.. o B .S .      |
|    + E  o       |
|                 |
|                 |
|                 |
+----[SHA256]-----+
[root@f2lctr01 ~]# packstack --gen-answer-file ~/answers.txt


[root@f2lctr01 ~]# packstack --answer-file ~/answers.txt
Welcome to the Packstack setup utility

The installation log file is available at: /var/tmp/packstack/20171220-111227-9tDkm_/openstack-setup.log

Installing:
Clean Up                                             [ DONE ]
Discovering ip protocol version                      [ DONE ]
Setting up ssh keys                                  [ DONE ]
Preparing servers                                    [ DONE ]
Pre installing Puppet and discovering hosts' details [ DONE ]
Preparing pre-install entries                        [ DONE ]
Installing time synchronization via NTP              [ DONE ]
Setting up CACERT                                    [ DONE ]
Preparing AMQP entries                               [ DONE ]
Preparing MariaDB entries                            [ DONE ]
Fixing Keystone LDAP config parameters to be undef if empty[ DONE ]
Preparing Keystone entries                           [ DONE ]
Preparing Glance entries                             [ DONE ]
Checking if the Cinder server has a cinder-volumes vg[ DONE ]
Preparing Cinder entries                             [ DONE ]
Preparing Nova API entries                           [ DONE ]
Creating ssh keys for Nova migration                 [ DONE ]
Gathering ssh host keys for Nova migration           [ DONE ]
Preparing Nova Compute entries                       [ DONE ]
Preparing Nova Scheduler entries                     [ DONE ]
Preparing Nova VNC Proxy entries                     [ DONE ]
Preparing OpenStack Network-related Nova entries     [ DONE ]
Preparing Nova Common entries                        [ DONE ]
Preparing Neutron LBaaS Agent entries                [ DONE ]
Preparing Neutron API entries                        [ DONE ]
Preparing Neutron L3 entries                         [ DONE ]
Preparing Neutron L2 Agent entries                   [ DONE ]
Preparing Neutron DHCP Agent entries                 [ DONE ]
Preparing Neutron Metering Agent entries             [ DONE ]
Checking if NetworkManager is enabled and running    [ DONE ]
Preparing OpenStack Client entries                   [ DONE ]
Preparing Horizon entries                            [ DONE ]
Preparing Swift builder entries                      [ DONE ]
Preparing Swift proxy entries                        [ DONE ]
Preparing Swift storage entries                      [ DONE ]
Preparing Heat entries                               [ DONE ]
Preparing Heat CloudWatch API entries                [ DONE ]
Preparing Heat CloudFormation API entries            [ DONE ]
Preparing Gnocchi entries                            [ DONE ]
Preparing MongoDB entries                            [ DONE ]
Preparing Redis entries                              [ DONE ]
Preparing Ceilometer entries                         [ DONE ]
Preparing Aodh entries                               [ DONE ]
Preparing Puppet manifests                           [ DONE ]
Copying Puppet modules and manifests                 [ DONE ]
Applying 10.12.8.11_controller.pp
10.12.8.11_controller.pp:                            [ DONE ]       
Applying 10.12.8.12_network.pp
Applying 10.12.8.11_network.pp
10.12.8.11_network.pp:                               [ DONE ]    
10.12.8.12_network.pp:                               [ DONE ]    
Applying 10.12.8.15_compute.pp
Applying 10.12.8.14_compute.pp
Applying 10.12.8.13_compute.pp
10.12.8.15_compute.pp:                               [ DONE ]    
10.12.8.13_compute.pp:                               [ DONE ]    
10.12.8.14_compute.pp:                               [ DONE ]    
Applying Puppet manifests                            [ DONE ]
Finalizing                                           [ DONE ]

 **** Installation completed successfully ******

Additional information:
 * File /root/keystonerc_admin has been created on OpenStack client host 10.12.8.11. To use the command line tools you need to source the file.
 * To access the OpenStack Dashboard browse to https://10.12.8.11/dashboard .
Please, find your login credentials stored in the keystonerc_admin in your home directory.
 * Because of the kernel update the host 10.12.8.15 requires reboot.
 * Because of the kernel update the host 10.12.8.14 requires reboot.
 * Because of the kernel update the host 10.12.8.12 requires reboot.
 * The installation log file is available at: /var/tmp/packstack/20171220-111227-9tDkm_/openstack-setup.log
 * The generated manifests are available at: /var/tmp/packstack/20171220-111227-9tDkm_/manifests





[root@f2lctr01 ~]# source keystonerc_admin 
[root@f2lctr01 ~(keystone_admin)]# cat keystonerc_admin 
unset OS_SERVICE_TOKEN
    export OS_USERNAME=admin
    export OS_PASSWORD=Actinver01
    export OS_AUTH_URL=http://10.12.8.11:5000/v2.0
    export PS1='[\u@\h \W(keystone_admin)]\$ '
    
export OS_TENANT_NAME=admin
export OS_REGION_NAME=RegionOne


[root@f2lctr01 ~(keystone_admin)]# openstack-service status
MainPID=8644 Id=neutron-dhcp-agent.service ActiveState=active
MainPID=8727 Id=neutron-l3-agent.service ActiveState=active
MainPID=8685 Id=neutron-lbaasv2-agent.service ActiveState=active
MainPID=8771 Id=neutron-metadata-agent.service ActiveState=active
MainPID=8605 Id=neutron-metering-agent.service ActiveState=active
MainPID=8565 Id=neutron-openvswitch-agent.service ActiveState=active
MainPID=6147 Id=neutron-server.service ActiveState=active
MainPID=28123 Id=openstack-aodh-evaluator.service ActiveState=active
MainPID=28040 Id=openstack-aodh-listener.service ActiveState=active
MainPID=28075 Id=openstack-aodh-notifier.service ActiveState=active
MainPID=29703 Id=openstack-ceilometer-central.service ActiveState=active
MainPID=29661 Id=openstack-ceilometer-collector.service ActiveState=active
MainPID=29622 Id=openstack-ceilometer-notification.service ActiveState=active
MainPID=29332 Id=openstack-cinder-api.service ActiveState=active
MainPID=29371 Id=openstack-cinder-backup.service ActiveState=active
MainPID=29447 Id=openstack-cinder-scheduler.service ActiveState=active
MainPID=29406 Id=openstack-cinder-volume.service ActiveState=active
MainPID=5697 Id=openstack-glance-api.service ActiveState=active
MainPID=5490 Id=openstack-glance-registry.service ActiveState=active
MainPID=28274 Id=openstack-gnocchi-metricd.service ActiveState=active
MainPID=28227 Id=openstack-gnocchi-statsd.service ActiveState=active
MainPID=6299 Id=openstack-heat-api-cfn.service ActiveState=active
MainPID=6420 Id=openstack-heat-api-cloudwatch.service ActiveState=active
MainPID=6373 Id=openstack-heat-api.service ActiveState=active
MainPID=6338 Id=openstack-heat-engine.service ActiveState=active
MainPID=0 Id=openstack-losetup.service ActiveState=active
MainPID=28923 Id=openstack-nova-api.service ActiveState=active
MainPID=28782 Id=openstack-nova-cert.service ActiveState=active
MainPID=29170 Id=openstack-nova-conductor.service ActiveState=active
MainPID=28874 Id=openstack-nova-consoleauth.service ActiveState=active
MainPID=28841 Id=openstack-nova-novncproxy.service ActiveState=active
MainPID=29114 Id=openstack-nova-scheduler.service ActiveState=active
MainPID=4223 Id=openstack-swift-account-auditor.service ActiveState=active
MainPID=3809 Id=openstack-swift-account-reaper.service ActiveState=active
MainPID=3853 Id=openstack-swift-account-replicator.service ActiveState=active
MainPID=3978 Id=openstack-swift-account.service ActiveState=active
MainPID=3896 Id=openstack-swift-container-auditor.service ActiveState=active
MainPID=3766 Id=openstack-swift-container-replicator.service ActiveState=active
MainPID=5987 Id=openstack-swift-container-updater.service ActiveState=active
MainPID=3939 Id=openstack-swift-container.service ActiveState=active
MainPID=4176 Id=openstack-swift-object-auditor.service ActiveState=active
MainPID=4127 Id=openstack-swift-object-expirer.service ActiveState=active
MainPID=4069 Id=openstack-swift-object-replicator.service ActiveState=active
MainPID=5736 Id=openstack-swift-object-updater.service ActiveState=active
MainPID=4023 Id=openstack-swift-object.service ActiveState=active
MainPID=5529 Id=openstack-swift-proxy.service ActiveState=active








[root@f2lctr01 ~(keystone_admin)]# nova hypervisor-list
+----+-----------------------------+-------+---------+
| ID | Hypervisor hostname         | State | Status  |
+----+-----------------------------+-------+---------+
| 1  | f2lcompute3.actinver.com.mx | up    | enabled |
| 2  | f2lcompute1.actinver.com.mx | up    | enabled |
| 3  | f2lcompute2.actinver.com.mx | up    | enabled |
+----+-----------------------------+-------+---------+




[root@f2lctr01 ~(keystone_admin)]# nova hypervisor-show f2lcompute1.actinver.com.mx
+---------------------------+------------------------------------------+
| Property                  | Value                                    |
+---------------------------+------------------------------------------+
| cpu_info_arch             | x86_64                                   |
| cpu_info_features         | ["pge", "avx", "xsaveopt", "clflush",    |
|                           | "sep", "syscall", "tsc-deadline",        |
|                           | "dtes64", "msr", "xsave", "vmx", "xtpr", |
|                           | "cmov", "pcid", "est", "pat", "monitor", |
|                           | "smx", "pbe", "lm", "tsc", "nx", "fxsr", |
|                           | "tm", "sse4.1", "pae", "sse4.2",         |
|                           | "pclmuldq", "acpi", "vme", "mmx",        |
|                           | "osxsave", "cx8", "mce", "de", "rdtscp", |
|                           | "ht", "dca", "lahf_lm", "pdcm", "mca",   |
|                           | "pdpe1gb", "apic", "sse", "pse", "ds",   |
|                           | "invtsc", "pni", "tm2", "aes", "sse2",   |
|                           | "ss", "ds_cpl", "arat", "ssse3", "fpu",  |
|                           | "cx16", "pse36", "mtrr", "popcnt",       |
|                           | "x2apic"]                                |
| cpu_info_model            | SandyBridge                              |
| cpu_info_topology_cells   | 2                                        |
| cpu_info_topology_cores   | 8                                        |
| cpu_info_topology_sockets | 1                                        |
| cpu_info_topology_threads | 2                                        |
| cpu_info_vendor           | Intel                                    |
| current_workload          | 0                                        |
| disk_available_least      | 47                                       |
| free_disk_gb              | 49                                       |
| free_ram_mb               | 130528                                   |
| host_ip                   | 10.12.8.13                               |
| hypervisor_hostname       | f2lcompute1.actinver.com.mx              |
| hypervisor_type           | QEMU                                     |
| hypervisor_version        | 2009000                                  |
| id                        | 2                                        |
| local_gb                  | 49                                       |
| local_gb_used             | 0                                        |
| memory_mb                 | 131040                                   |
| memory_mb_used            | 512                                      |
| running_vms               | 0                                        |
| service_disabled_reason   | None                                     |
| service_host              | f2lcompute1.actinver.com.mx              |
| service_id                | 22                                       |
| state                     | up                                       |
| status                    | enabled                                  |
| vcpus                     | 32                                       |
| vcpus_used                | 0                                        |
+---------------------------+------------------------------------------+




[root@f2lctr01 ~(keystone_admin)]# nova hypervisor-show f2lcompute2.actinver.com.mx
+---------------------------+------------------------------------------+
| Property                  | Value                                    |
+---------------------------+------------------------------------------+
| cpu_info_arch             | x86_64                                   |
| cpu_info_features         | ["pge", "avx", "xsaveopt", "clflush",    |
|                           | "sep", "syscall", "tsc-deadline",        |
|                           | "dtes64", "msr", "xsave", "vmx", "xtpr", |
|                           | "cmov", "pcid", "est", "pat", "monitor", |
|                           | "smx", "pbe", "lm", "tsc", "nx", "fxsr", |
|                           | "tm", "sse4.1", "pae", "sse4.2",         |
|                           | "pclmuldq", "acpi", "vme", "mmx",        |
|                           | "osxsave", "cx8", "mce", "de", "rdtscp", |
|                           | "ht", "dca", "lahf_lm", "pdcm", "mca",   |
|                           | "pdpe1gb", "apic", "sse", "pse", "ds",   |
|                           | "invtsc", "pni", "tm2", "aes", "sse2",   |
|                           | "ss", "ds_cpl", "arat", "ssse3", "fpu",  |
|                           | "cx16", "pse36", "mtrr", "popcnt",       |
|                           | "x2apic"]                                |
| cpu_info_model            | SandyBridge                              |
| cpu_info_topology_cells   | 2                                        |
| cpu_info_topology_cores   | 8                                        |
| cpu_info_topology_sockets | 1                                        |
| cpu_info_topology_threads | 2                                        |
| cpu_info_vendor           | Intel                                    |
| current_workload          | 0                                        |
| disk_available_least      | 47                                       |
| free_disk_gb              | 49                                       |
| free_ram_mb               | 130529                                   |
| host_ip                   | 10.12.8.14                               |
| hypervisor_hostname       | f2lcompute2.actinver.com.mx              |
| hypervisor_type           | QEMU                                     |
| hypervisor_version        | 2009000                                  |
| id                        | 3                                        |
| local_gb                  | 49                                       |
| local_gb_used             | 0                                        |
| memory_mb                 | 131041                                   |
| memory_mb_used            | 512                                      |
| running_vms               | 0                                        |
| service_disabled_reason   | None                                     |
| service_host              | f2lcompute2.actinver.com.mx              |
| service_id                | 23                                       |
| state                     | up                                       |
| status                    | enabled                                  |
| vcpus                     | 32                                       |
| vcpus_used                | 0                                        |
+---------------------------+------------------------------------------+



[root@f2lctr01 ~(keystone_admin)]# nova hypervisor-show f2lcompute3.actinver.com.mx
+---------------------------+------------------------------------------+
| Property                  | Value                                    |
+---------------------------+------------------------------------------+
| cpu_info_arch             | x86_64                                   |
| cpu_info_features         | ["pge", "avx", "xsaveopt", "clflush",    |
|                           | "sep", "syscall", "tsc-deadline",        |
|                           | "dtes64", "msr", "xsave", "vmx", "xtpr", |
|                           | "cmov", "pcid", "est", "pat", "monitor", |
|                           | "smx", "pbe", "lm", "tsc", "nx", "fxsr", |
|                           | "tm", "sse4.1", "pae", "sse4.2",         |
|                           | "pclmuldq", "acpi", "vme", "mmx",        |
|                           | "osxsave", "cx8", "mce", "de", "rdtscp", |
|                           | "ht", "dca", "lahf_lm", "pdcm", "mca",   |
|                           | "pdpe1gb", "apic", "sse", "pse", "ds",   |
|                           | "invtsc", "pni", "tm2", "aes", "sse2",   |
|                           | "ss", "ds_cpl", "arat", "ssse3", "fpu",  |
|                           | "cx16", "pse36", "mtrr", "popcnt",       |
|                           | "x2apic"]                                |
| cpu_info_model            | SandyBridge                              |
| cpu_info_topology_cells   | 2                                        |
| cpu_info_topology_cores   | 8                                        |
| cpu_info_topology_sockets | 1                                        |
| cpu_info_topology_threads | 2                                        |
| cpu_info_vendor           | Intel                                    |
| current_workload          | 0                                        |
| disk_available_least      | 47                                       |
| free_disk_gb              | 49                                       |
| free_ram_mb               | 130528                                   |
| host_ip                   | 10.12.8.15                               |
| hypervisor_hostname       | f2lcompute3.actinver.com.mx              |
| hypervisor_type           | QEMU                                     |
| hypervisor_version        | 2009000                                  |
| id                        | 1                                        |
| local_gb                  | 49                                       |
| local_gb_used             | 0                                        |
| memory_mb                 | 131040                                   |
| memory_mb_used            | 512                                      |
| running_vms               | 0                                        |
| service_disabled_reason   | None                                     |
| service_host              | f2lcompute3.actinver.com.mx              |
| service_id                | 21                                       |
| state                     | up                                       |
| status                    | enabled                                  |
| vcpus                     | 32                                       |
| vcpus_used                | 0                                        |
+---------------------------+------------------------------------------+




[root@f2lctr01 network-scripts]# ls
ifcfg-br-ex          ifcfg-enp12s0f6  ifdown-isdn      ifdown-tunnel  ifup-ovs     ifup-TeamPort
ifcfg-eno1.706       ifcfg-enp12s0f7  ifdown-ovs       ifup           ifup-plip    ifup-tunnel
ifcfg-enp0s29u1u1u5  ifcfg-lo         ifdown-post      ifup-aliases   ifup-plusb   ifup-wireless
ifcfg-enp12s0f1      ifdown           ifdown-ppp       ifup-bnep      ifup-post    init.ipv6-global
ifcfg-enp12s0f2.506  ifdown-bnep      ifdown-routes    ifup-eth       ifup-ppp     network-functions
ifcfg-enp12s0f3      ifdown-eth       ifdown-sit       ifup-ippp      ifup-routes  network-functions-ipv6
ifcfg-enp12s0f4      ifdown-ippp      ifdown-Team      ifup-ipv6      ifup-sit
ifcfg-enp12s0f5      ifdown-ipv6      ifdown-TeamPort  ifup-isdn      ifup-Team
[root@f2lctr01 network-scripts]# 
[root@f2lctr01 network-scripts]# 
[root@f2lctr01 network-scripts]# cat ifcfg-br-ex
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.11
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge
[root@f2lctr01 network-scripts]# 
[root@f2lctr01 network-scripts]# 
[root@f2lctr01 network-scripts]# cat ifcfg-enp12s0f2.506
DEVICE=enp12s0f2.506
NAME=enp12s0f2.506
DEVICETYPE=ovs
TYPE=OVSPort
OVS_BRIDGE=br-ex
ONBOOT=yes
BOOTPROTO=none
VLAN=yes

[root@f2lctr01 network-scripts]# ip r s
default via 10.12.8.254 dev br-ex 
10.10.205.0/24 dev eno1.706 proto kernel scope link src 10.10.205.19 
10.12.8.0/24 dev br-ex proto kernel scope link src 10.12.8.11 
169.254.0.0/16 dev eno1.706 scope link metric 1017 
169.254.0.0/16 dev enp12s0f2.506 scope link metric 1021 
169.254.0.0/16 dev br-ex scope link metric 1022











[root@f2lctr02 network-scripts]# ls ; cat ifcfg-br-ex
ifcfg-br-ex          ifcfg-enp12s0f4  ifdown-bnep  ifdown-post      ifdown-tunnel  ifup-ipv6   ifup-ppp       ifup-wireless
ifcfg-eno1.706       ifcfg-enp12s0f5  ifdown-eth   ifdown-ppp       ifup           ifup-isdn   ifup-routes    init.ipv6-global
ifcfg-enp0s29u1u1u5  ifcfg-enp12s0f6  ifdown-ippp  ifdown-routes    ifup-aliases   ifup-ovs    ifup-sit       network-functions
ifcfg-enp12s0f1      ifcfg-enp12s0f7  ifdown-ipv6  ifdown-sit       ifup-bnep      ifup-plip   ifup-Team      network-functions-ipv6
ifcfg-enp12s0f2.506  ifcfg-lo         ifdown-isdn  ifdown-Team      ifup-eth       ifup-plusb  ifup-TeamPort
ifcfg-enp12s0f3      ifdown           ifdown-ovs   ifdown-TeamPort  ifup-ippp      ifup-post   ifup-tunnel
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.12
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge

[root@f2lctr02 network-scripts]# cat ifcfg-enp12s0f2.506
DEVICE=enp12s0f2.506
NAME=enp12s0f2.506
DEVICETYPE=ovs
TYPE=OVSPort
OVS_BRIDGE=br-ex
ONBOOT=yes
BOOTPROTO=none
VLAN=yes

[root@f2lctr02 network-scripts]# ip r s
default via 10.12.8.254 dev br-ex 
10.10.205.0/24 dev eno1.706 proto kernel scope link src 10.10.205.20 
10.12.8.0/24 dev br-ex proto kernel scope link src 10.12.8.12 
169.254.0.0/16 dev eno1.706 scope link metric 1022 
169.254.0.0/16 dev enp12s0f2.506 scope link metric 1026 
169.254.0.0/16 dev br-ex scope link metric 1027 
[root@f2lctr02 network-scripts]# 








[root@f2lcompute1 network-scripts]# ls 
ifcfg-br-ex          ifcfg-enp12s0f4  ifdown-bnep  ifdown-ovs     ifdown-TeamPort  ifup-ib    ifup-plusb   ifup-TeamPort
ifcfg-eno1.706       ifcfg-enp12s0f5  ifdown-eth   ifdown-post    ifdown-tunnel    ifup-ippp  ifup-post    ifup-tunnel
ifcfg-enp0s29u1u1u5  ifcfg-enp12s0f6  ifdown-ib    ifdown-ppp     ifup             ifup-ipv6  ifup-ppp     ifup-wireless
ifcfg-enp12s0f1      ifcfg-enp12s0f7  ifdown-ippp  ifdown-routes  ifup-aliases     ifup-isdn  ifup-routes  init.ipv6-global
ifcfg-enp12s0f2.506  ifcfg-lo         ifdown-ipv6  ifdown-sit     ifup-bnep        ifup-ovs   ifup-sit     network-functions
ifcfg-enp12s0f3      ifdown           ifdown-isdn  ifdown-Team    ifup-eth         ifup-plip  ifup-Team    network-functions-ipv6
[root@f2lcompute1 network-scripts]# cat ifcfg-br-ex 
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.13
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge
[root@f2lcompute1 network-scripts]# 
[root@f2lcompute1 network-scripts]# 
[root@f2lcompute1 network-scripts]# 
[root@f2lcompute1 network-scripts]# cat ifcfg-br-ex
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.13
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge


[root@f2lcompute1 network-scripts]# ip r s
default via 10.12.8.254 dev br-ex 
10.10.205.0/24 dev eno1.706 proto kernel scope link src 10.10.205.21 
10.12.8.0/24 dev br-ex proto kernel scope link src 10.12.8.13 
169.254.0.0/16 dev enp0s29u1u1u5 scope link metric 1010 
169.254.0.0/16 dev eno1.706 scope link metric 1031 
169.254.0.0/16 dev enp12s0f2.506 scope link metric 1035 
169.254.0.0/16 dev br-ex scope link metric 1036 
169.254.95.0/24 dev enp0s29u1u1u5 proto kernel scope link src 169.254.95.120 











[root@f2lcompute2 network-scripts]# ls
ifcfg-br-ex          ifcfg-lo     ifdown-ppp       ifup-ib      ifup-sit
ifcfg-eno1.706       ifdown       ifdown-routes    ifup-ippp    ifup-Team
ifcfg-enp0s29u1u1u5  ifdown-bnep  ifdown-sit       ifup-ipv6    ifup-TeamPort
ifcfg-enp12s0f1      ifdown-eth   ifdown-Team      ifup-isdn    ifup-tunnel
ifcfg-enp12s0f2.506  ifdown-ib    ifdown-TeamPort  ifup-ovs     ifup-wireless
ifcfg-enp12s0f3      ifdown-ippp  ifdown-tunnel    ifup-plip    init.ipv6-global
ifcfg-enp12s0f4      ifdown-ipv6  ifup             ifup-plusb   network-functions
ifcfg-enp12s0f5      ifdown-isdn  ifup-aliases     ifup-post    network-functions-ipv6
ifcfg-enp12s0f6      ifdown-ovs   ifup-bnep        ifup-ppp
ifcfg-enp12s0f7      ifdown-post  ifup-eth         ifup-routes
[root@f2lcompute2 network-scripts]# cat ifcfg-br-ex 
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.14
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge
[root@f2lcompute2 network-scripts]# 
[root@f2lcompute2 network-scripts]# 
[root@f2lcompute2 network-scripts]# cat ifcfg-enp12s0f2.506
DEVICE=enp12s0f2.506
NAME=enp12s0f2.506
DEVICETYPE=ovs
TYPE=OVSPort
OVS_BRIDGE=br-ex
ONBOOT=yes
BOOTPROTO=none
VLAN=yes

[root@f2lcompute2 network-scripts]# ip r s
default via 10.12.8.254 dev br-ex 
10.10.205.0/24 dev eno1.706 proto kernel scope link src 10.10.205.23 
10.12.8.0/24 dev br-ex proto kernel scope link src 10.12.8.14 
169.254.0.0/16 dev eno1.706 scope link metric 1016 
169.254.0.0/16 dev enp12s0f2.506 scope link metric 1020 
169.254.0.0/16 dev br-ex scope link metric 1021 






[root@f2lcompute3 network-scripts]# ls
ifcfg-br-ex          ifcfg-lo     ifdown-ppp       ifup-ib      ifup-sit
ifcfg-eno1.706       ifdown       ifdown-routes    ifup-ippp    ifup-Team
ifcfg-enp0s29u1u1u5  ifdown-bnep  ifdown-sit       ifup-ipv6    ifup-TeamPort
ifcfg-enp12s0f1      ifdown-eth   ifdown-Team      ifup-isdn    ifup-tunnel
ifcfg-enp12s0f2.506  ifdown-ib    ifdown-TeamPort  ifup-ovs     ifup-wireless
ifcfg-enp12s0f3      ifdown-ippp  ifdown-tunnel    ifup-plip    init.ipv6-global
ifcfg-enp12s0f4      ifdown-ipv6  ifup             ifup-plusb   network-functions
ifcfg-enp12s0f5      ifdown-isdn  ifup-aliases     ifup-post    network-functions-ipv6
ifcfg-enp12s0f6      ifdown-ovs   ifup-bnep        ifup-ppp
ifcfg-enp12s0f7      ifdown-post  ifup-eth         ifup-routes
[root@f2lcompute3 network-scripts]# 
[root@f2lcompute3 network-scripts]# 
[root@f2lcompute3 network-scripts]# cat ifcfg-br-ex 
DEFROUTE=yes
ONBOOT=yes
IPADDR=10.12.8.15
PREFIX=24
GATEWAY=10.12.8.254
DEVICE=br-ex
NAME=br-ex
DEVICETYPE=ovs
OVSBOOTPROTO=static
TYPE=OVSBridge
[root@f2lcompute3 network-scripts]# 
[root@f2lcompute3 network-scripts]# 
[root@f2lcompute3 network-scripts]# cat ifcfg-enp12s0f2.506 
DEVICE=enp12s0f2.506
NAME=enp12s0f2.506
DEVICETYPE=ovs
TYPE=OVSPort
OVS_BRIDGE=br-ex
ONBOOT=yes
BOOTPROTO=none
VLAN=yes


[root@f2lcompute3 network-scripts]# ip r s
default via 10.12.8.254 dev br-ex 
10.10.205.0/24 dev eno1.706 proto kernel scope link src 10.10.205.24 
10.12.8.0/24 dev br-ex proto kernel scope link src 10.12.8.15 
169.254.0.0/16 dev eno1.706 scope link metric 1016 
169.254.0.0/16 dev enp12s0f2.506 scope link metric 1020 
169.254.0.0/16 dev br-ex scope link metric 1021 























issues

flushing device ethernet
ip addr flush dev enp12s0f2.406
flushing routing
echo 1  > /proc/sys/net/ipv4/flush













